### ISSUE TITLE
add art wiz logo

### ISSUE THREAD

**Issue by TrdHuy** [TrdHuy/ArtWiz#243]
![logo_500](https://github.com/TrdHuy/ArtWiz/assets/32306489/41347f8e-c041-4c28-a4a7-8bcac5f020c4)
![logo_1000](https://github.com/TrdHuy/ArtWiz/assets/32306489/ac8a0ffa-749a-49b9-8b0e-46e2194ca1ba)

**Comment by nqduy1** [comment]
# AS-IS
![image](https://github.com/TrdHuy/ArtWiz/assets/145240708/9c192dab-d0f5-4285-9824-1f1073eb5aa0)
# TO-BE
![image](https://github.com/TrdHuy/ArtWiz/assets/145240708/88768790-c9fb-49bf-8aa4-835064f9b0a1)
