### ISSUE TITLE
Apply UI version 1.4

### ISSUE THREAD

**Issue by TrdHuy** [TrdHuy/ArtWiz#253]

**Comment by nqduy1** [comment]
# AS-IS
![image](https://github.com/TrdHuy/ArtWiz/assets/145240708/192fa750-16fd-482e-a420-aec9b6e1b5a2)

# TO-BE
![image](https://github.com/TrdHuy/ArtWiz/assets/145240708/f0542ec7-654c-4324-81f3-4d768b7ab29c)
